### ISSUE TITLE
BMP Report - System Generated BMP Reports for all reports dated 2016 and prior

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Viewer#103]
It was discussed that all System Generated BMP Reports created for 2016 and prior be PDF copies of that particular years official BMP Inspection Report.  The reason for this is, BMP inspection methodology has changed over the years making some of the Auto Generated BMP Reports from 2016 and prior inaccurate.  PDF copies of these reports will be stored in a folder labelled by BMP Number and Inspection Year.  When a user selects a specific BMP for a specific year the system will then grab the PDF copy from the appropriate folder.  

Note:  All BMPs inspected from 2017 forward will generate using the existing viewer BMP report function and pull live from the database.

**Comment by leeensminger** [comment]
Brendan, this basically involves taking existing PDF documents that currently live somewhere on the M drive, and storing them somewhere the app can access them, and then linking them through our database relationships.  This represents new means of accessing reports that we'd have to wire up.

**Comment by KCI-Ablowers** [comment]
**From @mortynsky 8/13/2019** 

All,

Please see below for an update on Viewer Bug 103 in the DelDOT FY 19 Hours Estimate spreadsheet related to historical BMP reports from 2016 and prior:

1.	These reports are all located here:

\\\sparkssvm\DelDotPics\BMP_reports

2.	They are organized in the following manner
a.	Folder with the year inspected 
i.	i.e. 2009
3.	Within each inspection year folder there are PDFs with each BMP Inspection Report labeled in the following manner
a.	BMP_BMP_NUM
i.	i.e. BMP_20

I wanted to follow up from our discussion on 8/2 for documentation purposes.

Thanks,

Matt

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
I have this working in dev (according to my limited testing) and can move to prod whenever pending verification and approval.  (The code for BMP type - Sandfilter is in its own module and I updated comparably to the general BMP code, but just keep that in mind for testing and the existence of preexisting report files)

- There is no change to anything except the backend Python code.  When it is a post-2016 inspection selected, there is a new message "This is a post-2016 inspection and the PDF report will be generated dynamically...." and then things run as the have been.

- Otherwise the message is like " This is a pre-2017 inspection and the PDF report will be a copy of \\sparkssvm\DelDotPics\BMP_reports\2016\BMP_46.pdf"

- That root path is in the GP service's appConfig file as:  **pathForPre2017BMPpdfs = r'\\sparkssvm\DelDotPics\BMP_reports'** so now that is something to be aware going forward in case the server, path or permissions change.

- I am not doing anything conditional like checking for the file and generating dynamically if it does not exist.  If the database says there is an inspection for a BMP for a given pre-2017 year then the corresponding PDF file is assumed to exist by the path and naming convention and if the report fails it's a data issue.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Please see Gerrys comment above - https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/103#issuecomment-542373891. It may be worth testing and bringing in @mortynsky to take a look.

**Comment by cstevenson1** [comment]
@KCI-Ablowers Push to Prod. Matt and I reviewed the issue and believe Gerry's solution will meet our needs. Post 2017 reports appear to use the normal on-the-fly approach and pre-2017 reports appear to be pulling the static historical reports. Matt stated some BMPs have been renumbered so KCI Newark will need to renumber some PDFs in the location Gerry mentioned so they will properly open in the web viewer. For example BMP 2002 was renumbered to BMP 626 meaning the pre-2017 reports do not display for 626 because the historical PDF say 2002. Once again, KCI will handle renumbering the PDFs and it should not impact pushing to prod. Please let us know if the path for the documents change. 

![image](https://user-images.githubusercontent.com/16919898/67117313-64d92000-f1b0-11e9-91c7-5330525951e2.png)

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
Updated in Prod (note that inspections for sand filter BMPS are from BMP_DSF_INSPECTION_DRY and there are no pre-2017 inspections to test)

**Comment by KCI-Ablowers** [comment]
@cstevenson1 please confirm/test and close when you can.

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in PROD. Matt/Ryan will update the PDF names for BMPs where the BMP_Num has changed at \\sparkssvm\DelDotPics\BMP_reports as their availability permits.
