### ISSUE TITLE
Drop extraneous 0's in numerical values for advanced query builder and list sequentially 

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#12]
I noticed if you try to query a pipe segment based on its width that the value is a drop-down field as opposed to a manual type in. This limits the user since every possible value that could be searched is not in the drop-down (only contains values that are currently in database?). The values that are in it are also not in ascending order, making it less user friendly.

![image](https://cloud.githubusercontent.com/assets/16919898/25131591/4158ad92-2414-11e7-9005-1726d963d0ba.png)

This also applies to all other basic number fields like height.

**Comment by cstevenson1** [comment]
Per discussion with Bruce, he is fine leaving the field as a drop down if the 0's are dropped at the end of the number, if the numbers are sorted sequentially, and the field is a type ahead so when you type 36 you are automatically taken to the section of the drop down containing 36.

**Comment by cstevenson1** [comment]
After further testing, the field is allowing me to add the query statement with a typed in value or with a pre-defined one in the drop-down. This was not working for me yesterday but if this is the intended workflow then that can stay as is but the 0's will still need to be dropped and the numbers listed in sequential order. I will discuss making the type-ahead an enhancement with the team.

**Comment by leeensminger** [comment]
This is not a dropdown field.  This is text input, with type-ahead functionality already included.  The type ahead has a minimum character length before it displays a list of matching values; it appears this minimum is currently 3 characters.  The reason this is done, is because when you enter 3+ characters, the application goes back to the server to get the list of "everything starting with 292" or whatever your input is.  Then the server sends a list of values that match up to the UI.  So if you type "1" and expect to see a list of values, the server is going to send like 90,000 values to the UI.  Any UI will struggle to get those values, sort those values, render those values for the display, then display the list.  So you will visibly notice significant lag.

The bug here is to drop the zeroes.  The enhancement is to reduce the min text input length from 3 to 2 and see what the performance is like.

**Comment by leeensminger** [comment]
@kanglu666 please look into the extra zeroes.  also, please give us a level of effort to re-sort like [1, 2,3,4,5,6,7,8,9,10,11,12...19,20,21...99,100,101,102...]

**Comment by kanglu666** [comment]
the field type for the WIDTH in SQL is number(38,8), which by default has 8 precision. that's the reason the UI will get 8 extra zeroes back.
after testing:  the query "width = 2.00000000" will get the same results as query "width = 2"
1:  resort has been updated.
2: need to update the db schema for drop the zeroes, i think it's better leave as is.

**Comment by kanglu666** [comment]
updated, ready for testing in next release
