### ISSUE TITLE
Water Quality Investigation Report - Documentation section doesn't seem to be functioning properly

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#129]
In the DOCUMENTATION section of Form 1, Field Data Sheet is not checked even though it should be. Not sure if the others are functioning properly since they pertain to attachments and we do not have any attachments currently in the database. 

![image](https://user-images.githubusercontent.com/16919898/27971618-625110ba-6321-11e7-91d0-b7ccd16d39cf.png)

**Comment by leeensminger** [comment]
@cstevenson1 can you please provide a sample record where this is happening.  needed to replicate the issue

**Comment by cstevenson1** [comment]
See Structure 0111201141 as an example.

![image](https://user-images.githubusercontent.com/16919898/28117212-765b3efc-66da-11e7-8131-2c0e6a5e3b8f.png)

![image](https://user-images.githubusercontent.com/16919898/28117246-9adacc48-66da-11e7-90f8-fe11824ed584.png)

**Comment by cstevenson1** [comment]
Upon adding attachments in the Viewer, the Documentation section still does not appear to be functioning correctly. I attached Lab Results, Notice of Violation, Door Hanger and a Door Hanger Distribution Map to Structure 0111201141 and "Laboratory Data", "Door Hanger and Distribution Map", and "Notice of Potential Illicit Discharged" are not checked under the Documentation section when they should be. 

![image](https://user-images.githubusercontent.com/16919898/28582310-ed58b1e4-7132-11e7-9656-518601efcdbf.png)

![image](https://user-images.githubusercontent.com/16919898/28582348-037317c6-7133-11e7-8e67-835bbab23470.png)

**Comment by cstevenson1** [comment]
Additionally I added a "Miscellaneous Water Quality Investigation Document" attachments and "Other" was not checked in the Documentation Section. 

![image](https://user-images.githubusercontent.com/16919898/28584483-ec36cb04-713a-11e7-8e33-c6ee20767aa4.png)

![image](https://user-images.githubusercontent.com/16919898/28585833-9dc923cc-713f-11e7-9796-481061d6f132.png)

**Comment by gerrykelly** [comment]
@leeensminger 
This one is pending resolving where these records get into the [FILE_ATTACHMENT] table or not

**Comment by cstevenson1** [comment]
Bottom four check boxes are still not functioning.

**Comment by leeensminger** [comment]
@gerrykelly Not sure what you mean in your July 28 comment.  Can you elaborate?

**Comment by gerrykelly** [comment]
@leeensminger 
by "This one is pending resolving where these records get into the [FILE_ATTACHMENT] table or not" (I think I meant to type "whether", not where)  The issue is that FILE_ATTACHMENT_evw should have the same records as File_Attachments_Cloud (and I first search in FILE_ATTACHMENT_evw then get to the actual file by going through File_Attachments_Cloud)  I think I can now use File_Attachments_Cloud only and forget about File_Attachment (I'll revise the code and test if you agree that File_Attachment is not being maintained by the app, otherwise that is a separate issue to resolve
#164

**Comment by gerrykelly** [comment]
I believe this is now working correctly (but with our new file_attachment_cloud table for prod and the code having different config for the two environment, it should be separately verified in dev and prod)  Also note that that WQI related to Structure 0111201141 does not have the "OTHER" attachment type, but the box is getting checked correctly for the WQI that does globalID = 5B9BF4C2-DF37-41D1-9AC9-3CFA6253FF0A)

**Comment by cstevenson1** [comment]
I have not been able to get it to fully work. The checkboxes seem to be working but the document was not inserted in the report like it previously had when you added a file attachment.

Report before adding Lab Results
![image](https://user-images.githubusercontent.com/16919898/32342866-24f4c72a-bfd8-11e7-9659-45d24d2e7d37.png)

Report after adding Lab Results
![image](https://user-images.githubusercontent.com/16919898/32342893-32500970-bfd8-11e7-95af-0c2f9b656c80.png)

**Comment by leeensminger** [comment]
@cs I found this to be working fine for structure 0111201141.  Report attached:  [proxy.pdf](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/1440894/proxy.pdf)

Please provide an example where it's not working.

**Comment by cstevenson1** [comment]
Structure 0111201145

Structure 0111201141 is also working for us but already had attachments. We have not gotten it to work for WQI's where we are adding attachments for the first time. It only generates the field sheet.

**Comment by cstevenson1** [comment]
@leeensminger We are wondering if there is logic that we are unaware of. We tried testing some more and were able to add attachments for Structure 0111201140 and it worked properly. Was something included for flow vs no flow?

**Comment by cstevenson1** [comment]
Problem appears to be PDF vs non-PDF. Discussed and is a non-issue for WQI

**Comment by leeensminger** [comment]
Yes!  I apologies, as this has been the case for some time - any file type can be uploaded as an attachment into the viewer, but the WQ report specifically looks ONLY for PDFs.  The reason for this is because there is a significant amount of coding required to take non-pdf's and convert them into PDFs - plus there's the question of how would you handle non-convertable attachments such as videos, etc.  So we decided that for WQ investigations, PDFs are required. 

More than likely, this is the same response for #148
