### ISSUE TITLE
Add ability to search for community without selecting a layer

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#21]
Currently, to zoom to a subdivision in the new viewer, the user must select a layer in the geographic filter as shown below. However, if there are no features of that type within the subdivision, you cannot zoom to the area as shown in the image below as well (snip 1). It is an option we had in the previous viewer that users would like to keep (see snip 2).

Snip 1
![image](https://cloud.githubusercontent.com/assets/16919898/25236155/288d7e80-25b5-11e7-92f2-d5a07b2cd2bd.png)

Snip 2
![image](https://cloud.githubusercontent.com/assets/16919898/25236113/06f1fc4c-25b5-11e7-8c6a-0ba188ea07b6.png)

**Comment by leeensminger** [comment]
for discussion Thursday.

**Comment by cstevenson1** [comment]
Discussed with Lee and Sara on 3/26. See #222, #245, #246

**Comment by dobrochtaKCI** [comment]
@kanglu666 

We are going to add this functionality as a new query type called "Basemap Query" that will be included along with the canned query, geographic filters, and advanced query builder. The Basemap Query will allow the user to query the communities, bridges, flowlines (streams), and maintenance area layers from #222 #245 and #246 based on a single field. Each layer is using a different field to query the layer. 

 Since, we now have four query types to choose from (and potentially more in the future), we are also going to change the query selection from radio buttons along the top to a drop down selection button, because of space concerns related to adding another radio button along the top of the page.  

Since we are switching to a drop down we would like no query selected by default. We want to require the user to select the query type rather than automatically having the canned query enabled immediately after choosing the selections tab. 

I attached a wireframe to display the new design. Let me know if you have any questions about the frames. 
[New Query Functionality part 1.pdf](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/2106124/New.Query.Functionality.part.1.pdf)

**Comment by kanglu666** [comment]
start working on this one.

**Comment by kanglu666** [comment]
updated in dev, ready for testing in dev

**Comment by leeensminger** [comment]
@kanglu666 Can the action buttons be changed for the Base Map Query functions?  For all of these base map queries, "Trace Upstream" and "Load Details Information" action buttons do not apply.  Can they both be removed? (These two buttons should remain for other selections like Advanced Query and Geographic Filters).

**Comment by kanglu666** [comment]
@leeensminger  yes, i will hide those two button for the basemap query.

**Comment by kanglu666** [comment]
"Trace Upstream" and "Load Details Information" action buttons have been removed when perform the basemap query., 
Ready for testing in dev

**Comment by impittman** [comment]
The 2 action buttons have been removed from the basemap query in dev:
![image](https://user-images.githubusercontent.com/16418393/51679383-d632cc00-1fac-11e9-834c-04ff1a920118.png)

**Comment by impittman** [comment]
tested and appears to be working as expected in prod. @cstevenson1 please confirm prior to closing.

**Comment by cstevenson1** [comment]
General functionality seems fine. The drop-down does not work until you have typed in the first 3 characters but I think DelDOT will be ok with this to help speed I am assuming. However,

@leeensminger is there any customization to the display of the columns between query types? For example, can the "Type" default to showing for Advanced Query Builder but Not Base Map Query. With the base map queries you end up seeing the layer name twice (see snip below). Along those same lines, does it have to say Number? Is there a more generic term or other way to avoid having the community name under the number column.

![image](https://user-images.githubusercontent.com/16919898/52439159-de305700-2ae8-11e9-9dc8-0b433a065c08.png)

Also, same issue as with other queries where the results number does not update when you remove one from selection.

![image](https://user-images.githubusercontent.com/16919898/52439384-61ea4380-2ae9-11e9-94cf-d882d7d0e08c.png)

**Comment by leeensminger** [comment]
@kanglu666  Two issues:

**1. The results grid is not correct per the requirements.** 

The fields (columns) that should be shown are:
"Layer"
"Name/Number"

The fields (columns) that are currently shown are:
Layer
Number
Type
Ownership

**2. When a result item is removed from the results list, the count of records is not updated**

**Comment by kanglu666** [comment]
working on this one.

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by leeensminger** [comment]
@cstevenson1 please give it a test

**Comment by cstevenson1** [comment]
@leeensminger Last Edit Date and Ownership were not removed in Dev. I'm ok with leaving the Name column as is. 

![image](https://user-images.githubusercontent.com/16919898/54681585-2036ba80-4ae3-11e9-9ee2-332e5608e7b9.png)

Unable to test in Dev but I know in prod that you cannot easily switch between base map query and advanced query builder. If I use base map query to zoom to a community, I can switch to the advanced query builder and select by map but all 4 action buttons do not show which means you cannot open the feature details. Only the two action buttons from the base map query display.

![image](https://user-images.githubusercontent.com/16919898/54681955-02b62080-4ae4-11e9-96f6-0b50861f0704.png)

**Comment by leeensminger** [comment]
@impittman can you please translate this to specific, detailed actions for Lu?

**Comment by impittman** [comment]
@kanglu666 Please edit the following in Dev:
-In the Advanced Query Grid, remove the following items from the grid: 
         Last Edit Date
         Ownership
![image](https://user-images.githubusercontent.com/16418393/56424187-2dc79780-627d-11e9-878c-f412bc05886e.png)

-Please confirm that the the "select by map" option works in Advanced Query. When testing today (4/19), this feature was not available/working.

-The Advanced Query page needs to contain all 4 action buttons when the user "selects by map". Since I cannot get this function to work, please test and confirm that all 4 buttons in the Advanced Query grid appear when selecting by map.

**Comment by kanglu666** [comment]
Last Edit Date and Ownership columns have been removed , ready for testing in dev

**Comment by cstevenson1** [comment]
@KCI-Ablowers Ownership and Last Edit Date have been removed from the Advanced Query Builder and Base Map Query sections of the web viewer in Dev, however based on my 2/7 and 3/20 comments, it should have only been removed from the Base Map Query section since those fields do not apply. They are applicable and should be shown in the Advanced Query Builder. I can see where the confusion came from based on the 4/19 comment. This item was not targeted in the prioritized bug list but Ownership and Last Edit Date should be re-added in Dev. The main part of this issue was that the user could not use Base Map Query to navigate to a general area, such as a subdivision, and then use the Select by Map feature in the Advanced Query Builder section to open a feature (the Load Details Information button did not display in the Advanced Query Builder section). It appears this issue has since been resolved and the user is able to successfully toggle between the Base Map query and Advanced Query Builder with full functionality.

**Comment by KCI-Ablowers** [comment]
@kanglu666 Based on @cstevenson1 comment above https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/21#issuecomment-545433520 please add the Ownership and Last Edit Date fields back to the Advanced Query Builder.

**Comment by kanglu666** [comment]
Last Edit Date and Ownership columns have been added back

**Comment by kanglu666** [comment]
ready in PROD

**Comment by cstevenson1** [comment]
@KCI-Ablowers columns have been added back in. 
![image](https://user-images.githubusercontent.com/16919898/68026364-e5eee780-fc85-11e9-9ab7-8663145e43fc.png)

However, it is somewhat confusing for users that you can use the Select by Map feature in the Basemap Query work space and see Structures/Conveyances in the list but cannot open them. The user does not need to be able to open them though because Structures/Conveyances are not considered basemap data, which means they should not display in this work space. Ideally the user would be prompted to toggle to the Advanced Query Builder work space if they wanted to use the select by map feature but that is not a critical enhancement.

![image](https://user-images.githubusercontent.com/16919898/68026493-4aaa4200-fc86-11e9-92a6-e2c394e0a04d.png)

**Comment by cstevenson1** [comment]
@KCI-Ablowers this was addressed when defaulting select by map tool to the advanced query builder
