### ISSUE TITLE
BMP Reports - 2017 Photo on 2016 Report

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#235]
We have had a handful of BMP reports that are giving a server error in the viewer. We have been trying to figure it out for a while now and I finally noticed that the BMP photo that shows in the top right corner of the report is incorrect. The 2017 photo is showing on the 2016 report and the 2017 report is throwing the error. In the database the photos are properly associated so we aren't sure what happened. BMP 87 and 187 are examples.

![image](https://user-images.githubusercontent.com/16919898/35935078-5da8dcba-0c0d-11e8-9103-82f0eedcd2c2.png)

**Comment by gerrykelly** [comment]
@leeensminger 
There were actually two unrelated issues here:
1)  The photo shown was always from the latest inspection regardless of the year input.  This was correct from the original spec document.  You had flagged that as questionable, but the logic was never changed.  I have now updated it in dev and prod to get the most recent photo that is from an inspection with a date during or before the input year.
2) The server error was due to an inspected missing value related to Last Spillway Inspection.  I've handled that but like I've mentioned there is no blanket solution for things that pop up like this, so as they happen I need to debug and handle.

**Comment by cstevenson1** [comment]
When the inventory photo is present for the inspection it appears to be working properly. When there is not a 2018 photo (this should never be the case excluding just from human error) it still generates the report but uses the 2017 photo. I think this is fine because it should be picked up when we QC the BMP inspections. The snips below are for BMP 21 and I confirmed the photo on the 2017 report matches the photo attached to the 2017 inspection in the database and that there was no photo on the 2018 inspection. BMP 147 worked great where the 2016, 2017, and 2018 reports all generated with the proper photo.

2018 report with 2017 photo
![image](https://user-images.githubusercontent.com/16919898/39926706-04b351e6-54fe-11e8-9da1-0ca74cf5353f.png)

2017 report with 2017 photo

![image](https://user-images.githubusercontent.com/16919898/39926728-15be263c-54fe-11e8-9f98-d4e1647d1890.png)
