### ISSUE TITLE
Basemaps are not present in WQI Report Map

### ISSUE THREAD

**Issue by dobrochtaKCI** [leeensminger/DelDOT-NPDES-Viewer#271]
@gerrykelly There is currently an issue with the map that is generated for PID Point WQI Reports. The basemap in the report map is not displayed. The maps appears to be centered correctly on the PID point associated with the report, but neither the PID Point or the basemap is drawn.  I tested running the report with multiple PID Points as well as different basemaps toggled on in the map viewer at the time the report was generated, but that had no impact. We are not sure if this is related to the change in the number of basemap layers we currently have as a result of the label layers being added to the basemap layers service. I attached the report generated for PID Point 814 below.

Secondly, I noticed for PID points with no attachments or incident ID's  (PID Points 1, 2, 403 for example) no WQI reports are generated. I receive a server error 500- Internal Server error. I have a feeling this is related to the missing information in the WQI data, but wanted to confirm this is an expected issue. 

[PID_POINT_WQI_Report.pdf](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/2209796/PID_POINT_WQI_Report.pdf)

**Comment by gerrykelly** [comment]
@dobrochtaKCI 
The first part of this problem seems to be issues with 2 servers that provide the data.  I'll look into the rest when that is resolved.  I would not think the issues are specific for PID points only.

Also note that the reports do not use the map service at all.  They read from databases and the maps are generated through code using an mxd file.

**Comment by gerrykelly** [comment]
@dobrochtaKCI 
Now that the database is back up (noting that I still need to handle getting the basemap data back in the report) I think the problems you saw were due to:
1)  When I developed this, PID_POINTS were not ready to be included.  I turned on their display in the map so you will now see the feature.
2)  The rest was due to database issues,
         EXCEPT for PID Point 2.  This is an odd case where despite having a WQI there is no content for the report.  I am going to need to handle this in the geoprocess and
@leeensminger I guess we'll need to add a way for the UI to receive the message (or determine on its own) that a report cannot be generated because there is no content available.  Or maybe I just handle it on the GP side and generate a dummy report that explains there is no content for the report and if the user thinks that is in error they should contact the admin.

**Comment by leeensminger** [comment]
@gerrykelly  to answer your question - can you further clarify what you mean by "a report cannot be generated because there is no content available"?  I attempted to review Pid Point 2 to Pid Point 814 (the report generates fine for 814), but the viewer appears to be down and I cannot compare the two features.  When it is back up I can get back in and compare and get back to you.

**Comment by gerrykelly** [comment]
@leeensminger @dobrochtaKCI 
What I mean is that a feature will have a WQI associated with it, so from the UI it's assumed a report can be generated.  But then when the report GP runs because there is no incident_id, fieldsheet, memos, attachments (that are valid PDFs) there is nothing to put into the report doc.  
So what I did (in part to avoid needing to work on the UI side) is update the GP so that in this unusual case we can return a "report" PDF, but it simply says the following:

There was no content available to populate this report. If you believe this to be an error please raise it as an issue. (WQ Investigation -- OBJECTID = 12308)

**Comment by leeensminger** [comment]
@gerrykelly understood, now.  thanks for clarying.  I'm fine with this approach.  I see this is in prod, I'm assuming its in dev also.
