### ISSUE TITLE
BMP Report - Sand Filter Report Pulling Wrong Photo

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#273]
We can now generate 2018 sand filter reports but it appears it is pulling the photo from the 2017 inspection. See BMP 144 as an example. 

![image](https://user-images.githubusercontent.com/16919898/45949269-69410280-bfc9-11e8-8d9e-901f02c3abc1.png)

**Comment by gerrykelly** [comment]
@leeensminger 
I'm not sure why this was happening, but I updated the code slightly and I am getting the correct image every time.

**Comment by dobrochtaKCI** [comment]
@gerrykelly  I tested this and now the 2017 report for BMP#144 is using the inspection image from the 2018 inspection. I also checked this with the other BMP that currently has a 2018 BMP inspection, BMP# 538. This BMP has a 2018 inspection but no 2018 inspection photos. The 2018 report for BMP#538 will pull the 2017 inspection photo. It appears that the report is pulling the most current inspection photo with a Photo_Type of Overall Landscape. When it should be pulling the most recent photo with Photo_Type Overall landscape related that specific inspection record, not all the inspections photos related to the particular BMP. 

The sand filter reports also do not appear to be working in the dev viewer. I tried to generate a report for the 2017 inspection of BMP#144 and it returned a report titled (anonymous). 

Let me know if this needs clarification.  Thanks

**Comment by gerrykelly** [comment]
@dobrochtaKCI @leeensminger 
1)  I made the change to get the Overall Landscape photo for the sought BMP_DSF_INSPECTION_DRY inspection.  Using the most recent Overall Landscape (if any) when there was no Overall Landscape for the sought BMP_DSF_INSPECTION_DRY inspection was intentional but I don't remember why.  Now you will see a stock image labeled "Placeholder" instead.  I can create an "image" that has a message "No image available for this inspection" or something like that if desired.
2) So far as the issue with not getting a report for the 2017 BMP_DSF_INSPECTION_DRY info for BMP#144, I am looking into that, but it occurs to me that the code in the viewer might need to be updated to only present the user with the option to select an inspection year for sand filter bmps when a related BMP_DSF_INSPECTION_DRY for the year exists (otherwise the logic is based on if a BMP_INSPECTIONS record exists for all other BMP types) ... I don't know where Lu or Ehsan left off with that in the viewer

**Comment by gerrykelly** [comment]
@dobrochtaKCI @leeensminger 
The report failing in dev looks like it was an ArcGIS Server problem, not the GP code.  I restarted the service and it worked

**Comment by dobrochtaKCI** [comment]
The BMP report appear to be correctly pulling the Overall photo associated with the selected inspection year, and using a placeholder image where no inspection photos were attached to an inspection record.

@cstevenson1  please confirm this is working for you.

**Comment by cstevenson1** [comment]
Appears to be working properly.
