### ISSUE TITLE
Conveyance Report - Not pulling most recent inspection

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#288]
When a conveyance report is generated (for a pipe for example), the inspection information on the report should be from the most recent inspection and the photos included should only be from the most recent inspection. If there is a photo missing (Example -  there is an upstream photo but no downstream photo), only the photo associated with the recent inspection (upstream photo in this example) should be shown in the report. The report should not look at prior inspections to try and find a downstream photo. 

1. Example - Conveyance 0208210792: Has two inspections, one from 2009 and one from 2017. The last inspected date on the report says 9/8/2009 instead of 2017. The upstream photo is from the 2017 inspection and the downstream photo is from the 2009 inspection. The report should display the 2017 ratings and only have an upstream photo since we could not access the downstream during the 2017 inspection.
![image](https://user-images.githubusercontent.com/16919898/49819369-3b0acd80-fd43-11e8-9dec-c20478f0056e.png)

2. Example - Conveyance 0112015126: Has a 2018 and 2006 inspection. The 2006 data is shown with the 2018 photo.

3. Example - Conveyance 0207037305: Has a 2007 and 2018 inspection and it properly shows the 2018 data.

**Comment by gerrykelly** [comment]
@cstevenson1 @leeensminger 
I fixed the not-getting the latest inspection problem in dev and in prod.  Obviously this is a critical fix.  It was a bug where inspection date was being sorted as text rather than a date.  I found the same problem in one other place that was not yet observed as an issue and fixed there too.
The using the most recent up or down photo even if it's not from the latest inspection bug is a bit more involved but hopefully less critical so I'll leave this assigned to me also and fix ASAP

**Comment by cstevenson1** [comment]
Confirmed - report is now pulling the latest inspection info in prod and photos were left as is.

@gerrykelly Yes, you were right that the inspection info is more critical than the photos issue (still should be done with this milestone though). Thanks for taking care of that so quickly.

**Comment by cstevenson1** [comment]
Example referenced above appears to be fine in PROD now

![fsf](https://user-images.githubusercontent.com/16919898/51935301-99633c80-23d3-11e9-8f71-42b738318abf.png)
