### ISSUE TITLE
Remove type ahead for Structure and Conveyance ID

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#313]
Type ahead in the advanced query builder for Structure and Conveyance ID is slowing down search process and should be removed.

**Comment by leeensminger** [comment]
@cstevenson1  two options:
1) instead of triggering the type ahead list at 3 characters, we can trigger it at 4 or 5 characters.  so users have to type more before the list shows.  this is about 1 hour to do .
2) remove the type ahead altogether.  this is more complex than you and I originally though, and is about 16 hours total - basically, because we have to restructure the entire field and all the piping to be specific to structures and conveyances (all query fields are currently leveraging the same "build"... and we'd have to break that apart).

**Comment by cstevenson1** [comment]
option 1 is fine and just use the max number of characters possible before triggering the list (within that 1 hour to do range)

**Comment by kanglu666** [comment]
updated in dev, ready for testing

**Comment by cstevenson1** [comment]
Searching for ID is definitely faster than it was. Used conveyance 0112107720  and structure 0112117531 to test both manually entering and copying and pasting. Both methods of entry seemed faster than they were before. If 7 is the max number then this is good to push to prod.

**Comment by leeensminger** [comment]
@kanglu666 please push to prod

**Comment by kanglu666** [comment]
updated in PROD

**Comment by cstevenson1** [comment]
working in PROD
