### ISSUE TITLE
Struct/Convey WO Request - Unique KCIWONO logic

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#347]
Supreet (DelDOT) requires a unique KCIWONO per function code. If the function code is the same, a unique KCIWONO is not required.

The option presented include: 
1. Create logic to add in a "tag" ("_1", "_2", etc.) to the KCIWONO making it unique
2. Allow SQL to generate a new unique identifier that Supreet can consume in Maximo

@gerrykelly to determine the best method and move forward in Dev. 

Related to: #338

**Comment by gerrykelly** [comment]
@KCI-Ablowers
Updated in dev (both vm-deldotsql\deldot and deldot-sql2016) and prod

    The view WORK_ORDERS_MS4_withParentWO no longer exists and has been replaced by [WORK_ORDERS_MS4_Complete]

•	KCIWONO is now a unique ID for distinct workorder-function_code combinations (so, not a unique identifier in the scope of the table and is not intended to be)
o	I thought there was some value in having a meaningful ID with a consistent format rather than just generating one-off GUIDs or appending a sequence number only when needed.  So, the scheme is that:
	All KCIWONOs start with the 36 characters of the WORK_ORDER_ID and an underscore
	If a workorder has only one record, or multiple with all the same function code a “1” is appended
	Any records for the WO with differing function codes are sequenced as WORK_ORDER_ID + “_2”, “_3” … (with like-function_code values having the same sequence# of course)
	For the records with multiple problems codes (which used to involve the parent ID scheme) they are now WORK_ORDER_ID + “_M”

**Comment by cstevenson1** [comment]
@KCI-Ablowers @gerrykelly 

Confirmed KCIWONO is unique based on function code (through SQL Server Management Studio).

![image](https://user-images.githubusercontent.com/16919898/79877589-68956b80-83ba-11ea-9581-810fe30e30a3.png)
