### ISSUE TITLE
Struct/Conveyance Request - Submittal Automation

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#357]
To finalize the BMP and Struct/Conveyance "DelDOT requests" the quarterly submittals require an "automated submittal" process. 

Initial thoughts on the process include using a new or existing "status" field that indicates a set of records is ready to submit via the existing (to be modified) nightly script. The modified nightly script will continuously check for the agreed-upon "status" value and only push the records through when the condition(s) are met. This approach eliminates the need for a "magic button" and new GP scripts.

**Comment by cstevenson1** [comment]
@KCI-Ablowers As discussed in our meeting today, Matt and I agree with the proposed solution above. We were thinking we would have a status, such as "Pending" or "Under Review" to indicate work orders that need to be reviewed for the next submission. Once KCI Newark has reviewed them, we would update the status to "Approved" to indicate they are ready to be included in the nightly submission. Ideally, we would like SUBMITTED_DATE and SUBMITTED_YN to be updated automatically once the work order has been submitted to DelDOT.

**Comment by KCI-Ablowers** [comment]
@gerrykelly Let us know if this is not enough background information/ proposed process to get you started.

**Comment by gerrykelly** [comment]
I completed the logic and routine for exporting the workorders and deployed it in dev as follows:

•	The WO_PROBLEM_CODES_STATUS table now has the additional fields:
o	SEND_WITH_NIGHTLY_UPLOAD_YN
o	HAS_BEEN_UPLOADED_YN
o	COMMENTS
•	(Not that it matters in Dev, but I assume that running the GP task to update the WO_PROBLEM_CODES_STATUS table is now ingrained in your workflow)
•	The default value for SEND_WITH_NIGHTLY_UPLOAD_YN & HAS_BEEN_UPLOADED_YN is N (with only Y & N permitted)
•	When SEND_WITH_NIGHTLY_UPLOAD_YN is set to Y, any related records from WORK_ORDERS_MS4_Complete will now show up in a new view: WORK_ORDERS_MS4_Complete_TO_SEND
o	The new view is simply the same as the existing WORK_ORDERS_MS4_Complete, except for adding the highlighted clause below…
where STATUS='OPEN' and imd_action = 'No' and prob_code_gid in (SELECT GlobalID FROM [deldot_migration2].[dbo].[WO_PROBLEM_CODES_STATUS] where SEND_WITH_NIGHTLY_UPLOAD_YN='Y')
… which means that only records with matching WORK_ORDER_PROBLEM_CODES globalids (not displayed in the view), where SEND_WITH_NIGHTLY_UPLOAD_YN= ‘Y’ are included in WORK_ORDERS_MS4_Complete_TO_SEND
•	The nightly export routine now checks if there are records in the new view, and – if so – exports them as the table QUARTERLY_WORKORDER_SUBMITTAL in the DelDOT_NPDES_CoreData FGDB.
o	It then follows up by running the following SQL:
update [deldot_migration2].[dbo].[WO_PROBLEM_CODES_STATUS] set [SEND_WITH_NIGHTLY_UPLOAD_YN] = 'N', [HAS_BEEN_UPLOADED_YN] = 'Y', [SUBMITTED_YN]='Y', SUBMITTED_DATE = GETDATE()  where  SEND_WITH_NIGHTLY_UPLOAD_YN='Y'
	Note that the exported records will now be excluded from WORK_ORDERS_MS4_Complete because [SUBMITTED_YN]='Y' 
•	For testing, you can make edits, check WORK_ORDERS_MS4_Complete_TO_SEND. then – the next morning -- check the table C:\Projects\DelDOT_TSDM\DelDOT_TSDM_output\Core\Current\DelDOT_NPDES_CoreData.gdb on vm-deldot103
o	Once you a satisfied that the export works for you, I would suggest doing a couple mock submittals where the first night is like for Q1, the next for Q2, just to be sure that the logic and attributes support your workflow
•	To restore the views to the starting point, just run the following in SSMS:
update [deldot_migration2].[dbo].[WO_PROBLEM_CODES_STATUS] set SUBMITTED_DATE = null  , [HAS_BEEN_UPLOADED_YN] = 'N', [SUBMITTED_YN]='N', [SEND_WITH_NIGHTLY_UPLOAD_YN] = 'N'
