### ISSUE TITLE
Create Water Quality Investigation Report for Underdrain Pipe End

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#373]
Create a new Water Quality Investigation report for underdrain pipe ends. This should be identical to the existing WQI report for pipe ends.

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
There are no WQI records related to Underdrain Pipe Ends, but -- reviewing the code and SQL query -- it looks like it should work as-is.  I also expect that the code to call the report from the viewer also works as-is with Lu not needing to do anything specific due to the new structure type.
