### ISSUE TITLE
Create Water Quality Investigation Report for Underdrain Conveyance

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#375]
Create a new Water Quality Investigation report for underdrain conveyances. This should be identical to the existing WQI report for pipe conveyance features.

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
There are no WQI records related to Underdrain Conveyances but -- reviewing the code and SQL query -- it looks like it should work as-is.  I also expect that the code to call the report from the viewer also works as-is with Lu not needing to do anything specific due to the new Conveyance type.
