### ISSUE TITLE
Cannot Generate Feature Reports without Inspection

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#392]
DelDOT reported having sporadic issues generating feature reports. Structure 0304172750 was the example I was provided. After some troubleshooting, we believe it may be related to the lack of an inspection for features that include an inspection section on their report. For example, junction boxes do not get inspections and we have had no problems generating those reports. However, inlets do get inspections and we could not download reports for the 10 or so that we tried that did not have associated inspections. Seems to also be an issue for conveyances that have an inspection section like pipes.

Structure Examples
0110004808
0110003373
0208036312

Conveyance Examples
0110190768
0110322766

The inspection section can be populated with N/A or left blank. We are open to suggestions.

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
(odd that this never came up before ... I guess in development and testing the assumption was there was always at least one related inspection)

Updated in PROD so far as I think that reports work for the noted features and reports for features with inspection continue to work as they were.  But that only covers inlet & pipe and this problem is specific to each of inspection types, so I need to go in and make the same type of updates for each of the other feature subtype/inspection types.  I might do that first in dev (as is proper practice :-) )  I'll keep myself assigned until then and comment when done.

**Comment by KCI-Ablowers** [comment]
Thanks, @gerrykelly. I think making the updates for all types in Dev and testing is a good call. @cstevenson1 can you test the structures and conveyances you listed above in Prod to confirm the reports are working.

**Comment by cstevenson1** [comment]
@gerrykelly @KCI-Ablowers No inspection data of any sort is uncommon but it's even more uncommon for someone to generate that report because 99% of the time, the user is generating a report to gather all the inventory and inspection data (with the most recent photos) in one neat form.

Either way, the examples above are now working in prod. 

Just by looking at the table of contents, I know all conveyance types are capable of having an inspection and thus likely have the same issue excluding hydraulic connections. With the same thought for structures, these types have an inspection section in the report: inlets (fixed), manholes, pipe ends, control structures, culvert points, swale points (swale connections), underdrain pipe ends.

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
It turned out that it was only inspectionless inlets and pipes with this particular problem.  The updates for other subtypes were so minor and safe that I did it prod & dev.  
Also, seeing how some other queries we working without making the report fail, I revised the fix from yesterday (in prod and dev also) so that with no inspection, instead of omitting the section(s) I include it so far as inventory and component info (of course, with no inspection most of that info is likely to be blank anyway)

**Comment by KCI-Ablowers** [comment]
@gerrykelly I checked all of Christina's examples and was able to get a report successfully. @cstevenson1 Can you confirm and update or close the issue?

**Comment by cstevenson1** [comment]
confirmed they are now generating on our end. will close issue for now and reopen if new instances are reported
