### ISSUE TITLE
WQI Report - "Other" Photos Out of Order

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#396]
Currently in PROD, WQI photos in the report are ordered by category...Landscape, Structure, then Other. The Other photos are not ordered chronologically and the WQI team says they are also not arranged based on the order which they were entered, which should be consistent with the order of their OBJECTIDs. They would like the order to stay Landscape, Structure, Other BUT would like the Other photos to be ordered chronologically based on the date in the photo comment. Structure 0111034508 was the example provided.

The photo comment is currently formatted as "TEXT mm-dd-yy", however we can move the date to the front or change to a 4 digit year if that makes things easier. However, they will unlikely be able to go back and update original memos with photo comments to include dates. In these cases, we are fine with the photos being added like they are now (not chronological, OBJECTID?).

I've copied @gerrykelly email from 6/9/21 below:

Hi Christina, 

In working on this, when I got the SQL correct and put that logic into the report code, I saw that it was not that the images were in random order, it was that the routine queried by [WQI_PHOTO_CATEGORY] "Landscape", "Structure" then "Other" and the order within those groups probably always defaults to OBJECTID.  So likely that without splitting the pics up by category that they would already come out in chronological order if ordered by OBJECTID (I don’t know that for sure tho)

But, doing this properly as you had described would go something like this:
•	I query the photos all at once for the WQI, no longer splitting them by category
o	But, if there was/is a reason that they are split by category, we should probably stop here – but having already done the work here is how I did things:

•	As a test case let’s look at WQI 'D3E72BB8-95BA-48EC-917D-13A1EC28858E' in DEV (objectid 17192 related to structure No. 0112056628)
•	There are 8 related photos:
 
(BTW looking at the 8 photos in the report it sure looks like there are only 4 distinct ones with each having a duplicate, but that’s a question for another time)
•	As seen, my convention is to add, to comments the date (you could use 2-digit year if you prefer) preceded by the caret (not likely to ever show up in a comment otherwise, but you can come up with your own delimiter, or a rule that the date would always be the first or last text of a comment and no delimiter needed)
o	Then, I am able to convert that to a date and order the records by:
SELECT [WQI_PHOTO_COMMENTS]  FROM [deldot_migration2].[dbo].[WQI_INVESTIGATION_PHOTOS_evw] where WQ_INVESTIGATION_ID=  'D3E72BB8-95BA-48EC-917D-13A1EC28858E' 
order by try_convert(date,  SUBSTRING(replace(trim(WQI_PHOTO_COMMENTS),' ',''), CHARINDEX('^',replace(trim(WQI_PHOTO_COMMENTS),' ',''))+1,10) ,    110)
 
o	If a date cannot be extracted from the comment, the photo(s) go to the top, order by objectid

•	Now the photos in the report are ordered by date
•	I updated the routines in DEV for review
•	I am still displaying the full comment text, for the sake of testing, but imagine you would want that removed, or converted to like “ (Photo date 12-31-2019)”

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
I updated this in dev and prod with an order by clause of:

- order by (case WQI_PHOTO_CATEGORY when 'Landscape' then 1 when 'Structure' then 2 else  3 end ), isnull(try_convert(date, right(trim(ph.WQI_PHOTO_COMMENTS),8) , 10),'1/1/1900'), objectid 

Which means that photos will be ordered by:
- Landscape
- Structure
- Others with no date by objectid
- Others with date order by date (then objectid  if same date)

The query now looks for the date as MM-dd-yy in the **last 8 characters** of the comment
- So, the standard is like: "Trash in Catch Basin 11-03-20"
- Something like "Cigarettes in Catch Basin Behind Building (04-29-21)" (nor would having the comment end with a period for example).  Of course I can make the query more tolerant to handle things like this, but let's see if getting the date to conform in the comments works, as that is the preferred approach.
-  There are only 41 photos in PROD that have comments ending in MM-dd-yy.  But WQI with OBJECTID 27472 provides a partial test since there are 6 "other" photos with 3 different dates.

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 

I couldn't resist going back and updating the query to strip out parenthesis and periods when looking for the date.  So that is now fine (I can't see adding any more to the logic tho) WQI with object 26425 is a good test

**Comment by cstevenson1** [comment]
@gerrykelly @KCI-Ablowers WQI team checked a few in prod (limited options in dev due to outdated data) and are satisfied with how it is currently working.
