### ISSUE TITLE
Details Icon Not Available after Performing a Base Map Query and Select by Map

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#402]
When a user performs a base map query in the viewer then selects features on the map using the "Select by Map" tool, the details icon is not available in the feature list. This behavior is present in both the Dev and Prod viewers. User's should be able to view details for a selected feature from the feature list following this workflow. 

Steps to replicate:
- Perform base map query - Maintenance Areas / Magnolia.
- Zoom to maintenance area polygon (using Zoom to Location button).
- Select the "Select by Map" tool from the map toolbar and draw a square on the map to select features.
- The selected features load in the feature list with only the "Zoom to Location" and "Remove from Current Page" options being present. 

Feature list following a base map query and select by map - 
![image](https://user-images.githubusercontent.com/35460336/142049577-bb162f53-56e1-4e80-995c-9e1310105280.png)

Feature list following a geographic query (for comparison) -
![image](https://user-images.githubusercontent.com/35460336/142050087-c5b6a8f6-9abe-4078-9540-dfab33495449.png)

**Comment by KCI-Ablowers** [comment]
@kanglu666 took a look at this and came up with two options:

Option 1 -Leave as-is and introduce a workaround for viewing feature details. Users can perform the base map query to zoom to an area of interest, then switch to the advanced query builder before performing the select by map. Performing the select by map with the advanced query builder open presents the option to load details and trace features in the feature list. 

Option 2 - Review and update code to allow for details in the feature list following a Base Map Query --> Select by Map operation. @kanglu666 estimates 16 hours to make this update. 

@cstevenson1 we can review the options with the group and make a decision before proceeding.

**Comment by KCI-Ablowers** [comment]
@kanglu666 After talking with @cstevenson1 and the group, the update should get us a workflow like - Base map query --> drill down to AOI using zoom to location --> click select by map tool --> Make a selection on the Map --> Viewer flips the feature list to the advanced query builder with selected features. We think this would avoid you having to make any changes to the "Base Map Query" feature list and follows the functionality of other components. We can discuss this before you move forward.

**Comment by cstevenson1** [comment]
@KCI-Ablowers Preferably, we would want it to switch to the Advanced Query Builder panel whenever the user uses the Select by Map tool, not just within the Base Map Query. We ran it by DelDOT to make sure this would be satisfactory before abandoning option 2 and they like the idea (assuming it's feasible).

We told them...
-	We discussed the “Select by Map” within Base Map Query quirk and are exploring the option of having the viewer default the user to the Advanced Query Builder panel when the “Select by Map” tool is used. This would function similar to the “Identify” tool that toggles the user to the Identify panel when it is used. If this ends up being a viable option, this would allow the user to interact with their selected results (structures/conveyances/BMPs) regardless of what panel they were previously on (Base Map Query, Table of Contents, etc.).

**Comment by kanglu666** [comment]
updated.
if the user is in "Base Map Query" or "Canned Query" view. 
After using the "Select By Map" tool, they will be automatically redirect to "Advanced Query Builder" view. And also the selected features in the Map will show in the Advanced Query Builder.
Ready for testing in DEV,
https://devgis.kci.com/deldotwebviewer/index.html

NOTE: No changes in "Geographic Filters" since it support features query.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 confirmed working as expected from the base map query and canned query. Please test.

**Comment by cstevenson1** [comment]
@KCI-Ablowers the functionality appears to be working from base map query and canned query as Lu stated. However, per previous comment https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/402#issuecomment-977068780, we were hoping the process would be the same as identify where using 'Select by Map' would default you to the applicable workspace (advanced query builder in this case). Currently, the user is not toggled to advanced query builder if they are within any of the Table of Contents workspaces (Identify Results, Address Locator, Table of Contents).

If that is not feasible or is a large effort, we can leave as-is since the new process in dev is still a major improvement over the current process in PROD.

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by KCI-Ablowers** [comment]
@cstevenson1 I tested this in dev and I think it matches what you were expecting from our call. Please test.

**Comment by cstevenson1** [comment]
@KCI-Ablowers appears to be working as expected now. Please push to prod

**Comment by kanglu666** [comment]
Ready for testing in PRDO

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in prod. Using "Select by Map" tool toggles user to advanced query builder window with results showing. If features were already present in the list, the new results are appended.
