### ISSUE TITLE
Structure/Conveyance Report Pulling Photos from All Work ORders

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Viewer#411]
If there are more than one Work Order related to a Structure or Conveyance, the report pulls the information from the most recent Work order (correct) but it pulls the defect photos from ALL related Work Orders (wrong). For example, if there are three photos related to the old Work Order and two related to the new Work Order, the report is currently pulling all five defect photos but it should only pull the two photos from the new work order. 

Examples: 
Structure 0112049765
Structure 0112050526
Structure 0112050870
Conveyance 0111053715
Conveyance 0207083033
Conveyance 0109187697
Conveyance 0109326464

**Work Order Information section is pulling information from the newest work order (correct):** 
![image](https://user-images.githubusercontent.com/16919958/152835280-f1bba221-caf5-47e9-bf66-99e521776986.png)

**Report is including defect photos from both related work orders (incorrect). Should ONLY be photos related to newest record.**
![image](https://user-images.githubusercontent.com/16919958/152835552-5c02576d-cb4b-44ac-ba16-6f17e061385d.png)
![image](https://user-images.githubusercontent.com/16919958/152835617-c9cd17ba-5b84-424d-8281-ee48f667b102.png)

**Comment by gerrykelly** [comment]
@KCI-Ablowers 

@cstevenson1 I updated dev, but I did see the same issues for the structures in the list that I saw for the example conveyance.  So, please give it a test in dev, vs prod, and if you can give me an example where I can see a prod structure with pics from more than one WO, please do.  Otherwise if it seems to be working, it's just take a minute for me to update PROD

**Comment by mjuber-kci** [comment]
@gerrykelly The structures listed above are having the same issue on our end. The second structure listed (Structure 0112050526) has 0 photos for the old work order and 1 for the newer work order, so that is probably not the best example. However the other two structures are good examples.

Structure 0112049765 - two work orders present, each with 1 photo. Report is pulling 2 defect photos.
Structure 0112050870 - two work orders present, each with 2 photos. Report is pulling 4 defect photos.

**Comment by gerrykelly** [comment]
@mjuber-kci @KCI-Ablowers @cstevenson1 

OK see that in default production Structure 0112049765 is as described for work orders/photos.  I was trying to stay in DEV and that was not what I saw.  Anyway, I applied the update to PROD since it needs to be tester there.

The report went from ...
![image](https://user-images.githubusercontent.com/8259136/153083486-f6d90f4c-4ce6-4409-ba3c-39c16629d40f.png)

to:

![image](https://user-images.githubusercontent.com/8259136/153084080-7d6abb1e-f050-4597-8195-d0a68b1c3fad.png)

please check a couple structures (and again conveyances) that you've identified to see if this now works correctly

**Comment by cstevenson1** [comment]
@KCI-Ablowers @gerrykelly I spoke with @mjuber-kci and it appears to be functioning as expected now in PROD. Closing issue.
