### ISSUE TITLE
Update source for Comments field on Conveyance Report

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#421]
@KCI-Ablowers @gerrykelly currently, I believe the Comments field on the Conveyance report is sourced to PIPE_SEGMENTS.PIPES_COMMENTS or SWALES.SWALES_COMMENTS depending on the conveyance type. We have valuable information in the comments field on the feature class and would like to capture both comments on the report. Something along the lines of CONVEYANCES.LOC_COMMENTS + " " + PIPE_SEGMENTS.PIPES_COMMENTS / SWALES.SWALES_COMMENTS

![image](https://user-images.githubusercontent.com/16919898/175097321-5012d7a1-f935-4539-84af-655e14c7ce76.png)

**Comment by cstevenson1** [comment]
@gerrykelly Matt and I are good with what you have above (putting the entry on one line each instead of the current two). Please proceed. Can we also put the entry on one line instead of two for structure reports to make it consistent and give us more space with comments?

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
Update in PROD
- Structure reports already had those entries on one line
- When I tested in PROD for conveyance 0207318978, I did not get the conveyance LOC_COMMENTS in the report as seen in DEV.  It turned out that the code update was good, but those comments actually did not exist in PROD.  Does that make sense? (like is there updating going on in DEV as a test before it gets implemented in PROD, or would coincidentally someone have deleted that comments in prod?

**Comment by cstevenson1** [comment]
@gerrykelly @KCI-Ablowers 

Yes that makes sense. There is occasionally testing in Dev that would not necessarily also occur in Prod but it more probable that the comment was deleted in prod because it was no longer applicable. Comments are getting updated daily in Prod and Dev tends to be pretty outdated. 

Just to confirm, these revisions will carry over to conveyance reports generated through the GP tasks like multiReportStructConvey?

I am good closing this if you see no other issues.

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
Thanks for reminding me of multiReportStructConvey.  I hadn't thought of that and I have now updated dev and prod.

BTW, if it was not a GP service or I'd had 20/20 foresight anything that generates the same reports would use the same code files, but because of the beyond annoying way that you need to publish to ArcGIS Server, I'm stuck with needing to update for the specific task's Python files.

**Comment by cstevenson1** [comment]
@KCI-Ablowers I think we are good on this one. Will continue to monitor and will re-open if anything comes up.
